"""empty message

Revision ID: 39175db07ca7
Revises: 0763d677d453
Create Date: 2026-02-10 15:20:27.759090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39175db07ca7'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('user_name', sa.String(length=120), nullable=True))
        batch_op.drop_column('password')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('user_name')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
